# Generated by Django 2.0.5 on 2018-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
