# Generated by Django 2.0.5 on 2018-05-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180526_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='Text',
        ),
    ]
